### ISSUE TITLE
laravel 5.7

### ISSUE THREAD

**Issue by kakarias** [cmdobueno/route-priority#1]
Hi, it is possible update this library for laravel 5.7? thank you.

**Comment by cmdobueno** [comment]
To be honest, I have pretty much abandoned this package.

You can do a pull request and I will update it though! (I did not realize anybody was using this)

**Comment by cmdobueno** [comment]
@kakarias I have updated the requirements, as well as I have updated auto-discovery since I was working on it, figured might as well get things going. 

If you have further issues with the package on laravel 5.7 please let me know... I have not tested this package on 5.7.
